BE/ai-server/classification/urls.py
from django.urls import path
from . import views

app_name = 'classification'

urlpatterns = [
    path('index', views.index, name='index'),
    path('male', views.male, name='male'),
    path('female', views.female, name='female'),
    path('imageinput', views.imageinput, name='imageinput'),
    path('imagechoice', views.imagechoice, name='imagechoice'),
    path('resultoutput', views.resultoutput, name='resultoutput'),
    path('emotion', views.emotion, name='emotion'),
    path('emotioninput', views.emotioninput, name='emotioninput'),
    path('emotionchoice', views.emotionchoice, name='emotionchoice'),
    path('emotionoutput', views.emotionoutput, name='emotionoutput'),
]

BE/ai-server/config/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classification/', include('classification.urls')),
]

BE/ai-server/classification/models.py
from django.db import models

# Create your models here.

BE/ai-server/classification/forms.py
from django import forms

BE/ai-server/classification/views.py
from django.shortcuts import render, redirect
from PIL import Image
from preprocessing import preprocessing_face_cascade
from preprocessing_emotion import preprocessing_face_cascade_emotion
from glob import glob

import torch
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import Dataset, DataLoader
from skimage import io, transform

from female_test import get_label
from female_test import MyCifarSet
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from django.http  import JsonResponse

from django.views.decorators.csrf import csrf_exempt

import json

import base64
from PIL import Image
from io import BytesIO
import matplotlib.pyplot as plt

import os
# Create your views here.
def saveimage(path, gender):
    # print(path)
    image = Image.open(path)
    image_convert = image.convert("RGB")
    image_convert.save('/home/ubuntu/S05P21C105/BE/ai-server/classification/data/' + gender + '/inputimage.jpg')
    return None
# /home/ubuntu/S05P21C105/BE/ai-server/

def saveimage_emotion(path):
    image = Image.open(BytesIO(base64.b64decode(path)))
    # image = Image.open(path)
    image_convert = image.convert("RGB")
    os.remove('/home/ubuntu/S05P21C105/BE/ai-server/classification/data_emotion/inputimage.jpg')
    # width, height = image_convert.size
    # print(height)
    # print(width, height)
    # image_convert = image_convert.resize((int(image_convert.width * 2), int(image_convert.height * 2)))
    # width, height = image_convert.size
    # print(width, height)
    image_convert.save('/home/ubuntu/S05P21C105/BE/ai-server/classification/data_emotion/inputimage.jpg')
    # with open('/home/ubuntu/S05P21C105/BE/ai-server/classification/data_emotion/inputimage.jpg', 'rb') as img:
    #     base64_string = base64.b64encode(img.read())
    # print(str(base64_string)[:300])
    return None

transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

def get_label(data_path_list):
    label_list = []
    for path in data_path_list:
        # 뒤에서 두번째가 class다.
        label_list.append(path.split('/')[-2])
    return label_list

class MyCifarSet(Dataset):
    #data_path_list - 이미지 path 전체 리스트
    #label - 이미지 ground truth
    def __init__(self, data_path_list, classes, transform=None):
        self.path_list = data_path_list
        self.label = get_label(data_path_list)
        self.transform = transform
        self.classes = classes
        
    def __len__(self):
        return len(self.path_list)

    def __getitem__(self, idx):
        if torch.is_tensor(idx):
            idx = idx.tolist()
        image = io.imread(self.path_list[idx])
        if self.transform is not None:
            image = self.transform(image)
        return image, self.classes.index(self.label[idx])



def index(request):
    return render(request, 'classification/index.html')

def male(request):
    return render(request, 'classification/male.html')

def female(request):
    return render(request, 'classification/female.html')

def imageinput(request):
    return render(request, 'classification/imageinput.html')

def imagechoice(request):
    # data받기
    gender = request.POST['gender']
    path = request.POST['path']


    saveimage(path, gender)
    # 전처리
    try:
        count = preprocessing_face_cascade(gender)
        print(count)
        # if count == 0:
        #     # print("얼굴없음")
        # elif count == 1:
        #     pass
        #     # print("얼굴 1")
        # else:
        #     pass
        #     # print("얼굴많음")
        # # print("전처리함")
        
    except:
        print("전처리실패함")
    if gender == 'male':
        classes = ('bear', 'dinosour', 'dog', 'horse', 'rabbit', 'wolf')
    elif gender == 'female':
        classes = ('cat', 'deer', 'dog', 'fox', 'rabbit', 'squirtle')
    # print(classes)
    # 이미지분류
    DATA_PATH_TESTING_LIST = glob('.\\classification\\preprocessed\\'+ gender +'\\*\\*.jpg')
    # print(DATA_PATH_TESTING_LIST)

    testloader = torch.utils.data.DataLoader(
        MyCifarSet(
            DATA_PATH_TESTING_LIST, 
            classes,
            transform=transform
        ),
        batch_size=4,
        shuffle = False
    )
    class Net(nn.Module):
        def __init__(self):
            super().__init__()
            self.conv1 = nn.Conv2d(3, 6, 5)
            self.pool = nn.MaxPool2d(2, 2)
            self.conv2 = nn.Conv2d(6, 16, 5)
            self.fc1 = nn.Linear(256, 120)
            self.fc2 = nn.Linear(120, 84)
            self.fc3 = nn.Linear(84, 10)

        def forward(self, x):
            x = self.pool(F.relu(self.conv1(x))) 
            x = self.pool(F.relu(self.conv2(x)))
            x = torch.flatten(x, 1) 
            x = F.relu(self.fc1(x))
            x = F.relu(self.fc2(x))
            x = self.fc3(x)
            return x

    net = Net()

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)


    dataiter = iter(testloader)
    images, labels = dataiter.next()

    net = Net()
    if gender == 'female':
        net.load_state_dict(torch.load(".\\classification\\cifar_net_female_2.pth"))
    elif gender == 'male':
        net.load_state_dict(torch.load(".\\classification\\cifar_net_male_3.pth"))
    # net.load_state_dict(torch.load(".\\classification\\cifar_net_female_2.pth"))
    outputs = net(images)

    _, predicted = torch.max(outputs, 1)

    # print('Predicted: ', ' '.join('%s' % classes[predicted[j]] for j in range(1)))

    result = ' '.join('%s' % classes[predicted[j]] for j in range(1))

    if result == 'dinosour':
        result = 'dinosaur'
    image_path_input = './classification/data/' + gender + '/inputimage.jpg'
    image_path_dog = './classification/preprocessed/' + gender + '/dog/1.jpg'
    context = {
        'result': result,
        'gender': gender,
        'image_path_input': image_path_input,
        'image_path_dog': image_path_dog,        
    }
    # return render(request, 'classification/resultoutput.html', context)
    json_object = { 'result': result, 'gender': gender}
    return JsonResponse(json_object)

@csrf_exempt
def resultoutput(request):
    # data받기
    gender = json.loads(request.body)['gender'][0]
    path = json.loads(request.body)['path'][0]
    # gender = request.POST.get("gender", None)
    # path = request.POST.get("path", None)
    # gender = request.POST['gender']
    # # # print(request.POST)
    # path = request.POST['path']

    # gender = request.POST.get("gender")
    # path = request.POST.get("path")
    # print("mmmmmmmmmmmmmmmmmmm")
    print(gender, path)
    # gender = request.headers['gender']
    # path = request.headers['path']

    saveimage(path, gender)
    # 전처리
    try:
        count = preprocessing_face_cascade(gender)
        # if count == 0:
        #     print("얼굴없음")
        # elif count == 1:
        #     print("얼굴 1")
        # else:
        #     print("얼굴많음")
        # print("전처리함")
        
    except:
        pass
        # print("전처리실패함")
    if gender == 'male':
        classes = ('bear', 'dinosour', 'dog', 'horse', 'rabbit', 'wolf')
    elif gender == 'female':
        classes = ('cat', 'deer', 'dog', 'fox', 'rabbit', 'squirtle')
    # print(classes)
    # 이미지분류
    DATA_PATH_TESTING_LIST = ['classification/preprocessed/female/dog/1.jpg']
    # print(DATA_PATH_TESTING_LIST)

    testloader = torch.utils.data.DataLoader(
        MyCifarSet(
            DATA_PATH_TESTING_LIST, 
            classes,
            transform=transform
        ),
        batch_size=4,
        shuffle = False
    )
    class Net(nn.Module):
        def __init__(self):
            super().__init__()
            self.conv1 = nn.Conv2d(3, 6, 5)
            self.pool = nn.MaxPool2d(2, 2)
            self.conv2 = nn.Conv2d(6, 16, 5)
            self.fc1 = nn.Linear(256, 120)
            self.fc2 = nn.Linear(120, 84)
            self.fc3 = nn.Linear(84, 10)

        def forward(self, x):
            x = self.pool(F.relu(self.conv1(x))) 
            x = self.pool(F.relu(self.conv2(x)))
            x = torch.flatten(x, 1) 
            x = F.relu(self.fc1(x))
            x = F.relu(self.fc2(x))
            x = self.fc3(x)
            return x

    net = Net()

    criterion = nn.CrossEntropyLoss()
    optimizer = optim.SGD(net.parameters(), lr=0.001, momentum=0.9)


    dataiter = iter(testloader)
    images, labels = dataiter.next()

    net = Net()
    if gender == 'female':
        net.load_state_dict(torch.load("/home/ubuntu/S05P21C105/BE/ai-server/classification/cifar_net_female_2.pth"))
    elif gender == 'male':
        net.load_state_dict(torch.load("/home/ubuntu/S05P21C105/BE/ai-server/classification/cifar_net_male_3.pth"))
    # net.load_state_dict(torch.load(".\\classification\\cifar_net_female_2.pth"))
    outputs = net(images)

    _, predicted = torch.max(outputs, 1)

    # print('Predicted: ', ' '.join('%s' % classes[predicted[j]] for j in range(1)))

    result = ' '.join('%s' % classes[predicted[j]] for j in range(1))

    if result == 'dinosour':
        result = 'dinosaur'
    if count == 0:
        result == "None"
    print(result)
    image_path_input = '/home/ubuntu/S05P21C105/BE/ai-server/classification/data/' + gender + '/inputimage.jpg'
    image_path_dog = '/home/ubuntu/S05P21C105/BE/ai-server/classification/preprocessed/' + gender + '/dog/1.jpg'
    context = {
        'result': result,
        'gender': gender,
        'image_path_input': image_path_input,
        'image_path_dog': image_path_dog,        
    }
    # return render(request, 'classification/resultoutput.html', context)
    json_object = { 'result': result, 'gender': gender}
    return JsonResponse(json_object)


def emotion(request):
    return render(request, 'classification/emotion.html')

def emotioninput(request):
    return render(request, 'classification/emotioninput.html')

def emotionchoice(request):
    # data받기

BE/ai-server/classification/templates/classification/emotionchoice.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="">
    <head>
        <!-- meta charset -->
        <meta charset="utf-8">
        <!-- site title -->
        <title>Phantom | Personal Resume Template</title>
        <!-- meta description -->
        <meta name="description" content="">
        <!-- mobile viwport meta -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- fevicon -->
        <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
        
        <!-- ================================
        CSS Files
        ================================= -->
        <link href="https://fonts.googleapis.com/css?family=Libre+Baskerville:400,400i|Open+Sans:400,600,700,800" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/themefisher-fonts.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link id="color-changer" rel="stylesheet" href="{% static 'css/colors/color-0.css' %}">
    </head>

    <body>

        <div class="preloader">
            <div class="loading-mask"></div>
            <div class="loading-mask"></div>
            <div class="loading-mask"></div>
            <div class="loading-mask"></div>
            <div class="loading-mask"></div>
        </div>

        <!-- <div class="preview-wrapper">
            <div class="switcher-head">
                <span>Style Switcher</span>
                <div class="switcher-trigger tf-tools"></div>
            </div>

            <div class="switcher-body">
                <h4>Choose Color:</h4>
                <ul class="color-options list-none">
                    <li class="c0" data-color="red" title="Default">Default</li>
                    <li class="c1" data-color="blue" title="Red">Red</li>
                    <li class="c2" data-color="green" title="Green">Green</li>
                    <li class="c3" data-color="yellow" title="Blue">Blue</li>
                </ul>
            </div>
        </div> -->

        <main class="site-wrapper">
            <div class="pt-table">
                <div class="pt-tablecell page-contact relative">
                    <!-- .close -->
                    <a href="./" class="page-close"><i class="tf-ion-close"></i></a>
                    <!-- /.close -->

                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12 col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8">
                                <div class="page-title text-center">
                                    <h2>Image  <span class="primary">choice</span> <span class="title-bg">predict</span></h2>
                                 
                                </div>
                            </div>                            
                        </div> <!-- /.row -->

                        <div class="row">
                            <div class="col-xs-12 col-sm-5 col-md-4 col-lg-3">
                                <div class="contact-block">
                                    <div class="media">
                                        <div class="media-left">
                                            <i class="tf-envelope2"></i>
                                        </div>
                                        <div class="media-body">
                                            <h4>Email</h4>
                                            <p><a href="mailto:my_name@gmail.com">my_name@gmail.com</a></p>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.contact-block -->
                                <div class="contact-block">
                                    <div class="media">
                                        <div class="media-left">
                                            <i class="tf-phone2"></i>
                                        </div>
                                        <div class="media-body">
                                            <h4>Phone</h4>
                                            <p><a href="tel:+000-1111-2222">+000-1111-2222</a></p>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.contact-block -->
                                <div class="contact-block">
                                    <div class="media">
                                        <div class="media-left">
                                            <i class="tf-mobile"></i>
                                        </div>
                                        <div class="media-body">
                                            <h4>Skype</h4>
                                            <p><a href="skype:my_name">my_name</a></p>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.contact-block -->

                                <ul class="contact-social">
                                    <li>
                                        <span class="contact-social-hex"></span>
                                        <a href="www.fb.com/themefisher"><i class="tf-ion-social-facebook"></i></a>
                                    </li>
                                    <li>
                                        <span class="contact-social-hex"></span>
                                        <a href="www.twitter.com/themefisher"><i class="tf-ion-social-twitter"></i></a>
                                    </li>
                                    <li>
                                        <span class="contact-social-hex"></span>
                                        <a href="#"><i class="tf-ion-social-google"></i></a>
                                    </li>
                                    <li>
                                        <span class="contact-social-hex"></span>
                                        <a href="www.dribbble.com/themefisher"><i class="tf-ion-social-dribbble"></i></a>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-xs-12 col-sm-7 col-md-7 col-md-offset-1 col-lg-offset-2">
                                <div class="section-title clear">
                                    <h3>Send Image</h3>
                                    <span class="bar-dark"></span>
                                    <span class="bar-primary"></span>
                                </div>

                                <form id="contact-form" class="row contact-form no-gutter" action="{% url 'classification:imagechoice' %}" method="post">
                                    
                                    <div class="col-xs-12 col-sm-12">
                                        <div class="input-field">
                                            <span class= "input-icon" id="subject"><i class="tf-pricetags"></i></span>
                                            <input type="text" class="form-control" name="subject" placeholder="Image path">
                                        </div>
                                    </div> <!-- ./col- -->
                                    
                                    <div class="col-xs-12 col-sm-12">
                                        <div class="input-field">
                                            <span class= "input-icon" id="subject"><i class="tf-pricetags"></i></span>
                                            <input type="text" class="form-control" name="subject" placeholder="Gender">
                                        </div>
                                    </div> <!-- ./col- -->
                                    <div class="col-xs-12 col-sm-12">
                                        <div class="input-field">
                                            <span class="btn-border">
                                                <button type="submit" class="btn btn-primary btn-custom-border text-uppercase">Send Image</button>
                                            </span>
                                        </div>
                                    </div> <!-- ./col- -->
                                </form> <!-- /.row -->
                            </div> <!-- /.col- -->
                        </div> <!-- /.row -->
                        
                    </div> <!-- /.container -->

                    
                    <!-- /.container -->

                </div> <!-- /.pt-tablecell -->
            </div> <!-- /.pt-table -->
        </main> <!-- /.site-wrapper -->

        <!-- ================================
        JavaScript Libraries
        ================================= -->
        <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.easing.min.js' %}"></script>
        <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/jquery-validation.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

BE/ai-server/classification/templates/classification/emotioninput.html
{% load static %}
<!DOCTYPE html>
<html class="no-js" lang="">
    <head>
        <!-- meta charset -->
        <meta charset="utf-8">
        <!-- site title -->
        <title>Phantom | Personal Resume Template</title>
        <!-- meta description -->
        <meta name="description" content="">
        <!-- mobile viwport meta -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- fevicon -->
        <link rel="shortcut icon" type="image/x-icon" href="favicon.ico">
        
        <!-- ================================
        CSS Files
        ================================= -->
        <link href="https://fonts.googleapis.com/css?family=Libre+Baskerville:400,400i|Open+Sans:400,600,700,800" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/themefisher-fonts.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link id="color-changer" rel="stylesheet" href="{% static 'css/colors/color-0.css' %}">
    </head>

    <body>

        <div class="preloader">
            <div class="loading-mask"></div>
            <div class="loading-mask"></div>
            <div class="loading-mask"></div>
            <div class="loading-mask"></div>
            <div class="loading-mask"></div>
        </div>

        <!-- <div class="preview-wrapper">
            <div class="switcher-head">
                <span>Style Switcher</span>
                <div class="switcher-trigger tf-tools"></div>
            </div>

            <div class="switcher-body">
                <h4>Choose Color:</h4>
                <ul class="color-options list-none">
                    <li class="c0" data-color="red" title="Default">Default</li>
                    <li class="c1" data-color="blue" title="Red">Red</li>
                    <li class="c2" data-color="green" title="Green">Green</li>
                    <li class="c3" data-color="yellow" title="Blue">Blue</li>
                </ul>
            </div>
        </div> -->

        <main class="site-wrapper">
            <div class="pt-table">
                <div class="pt-tablecell page-contact relative">
                    <!-- .close -->
                    <a href="./" class="page-close"><i class="tf-ion-close"></i></a>
                    <!-- /.close -->

                    <div class="container">
                        <div class="row">
                            <div class="col-xs-12 col-md-offset-1 col-md-10 col-lg-offset-2 col-lg-8">
                                <div class="page-title text-center">
                                    <h2>Emotion  <span class="primary">input</span> <span class="title-bg">predict</span></h2>
                                 
                                </div>
                            </div>                            
                        </div> <!-- /.row -->

                        <div class="row">
                            <div class="col-xs-12 col-sm-5 col-md-4 col-lg-3">
                                <div class="contact-block">
                                    <h2>result: {{ result }}</h2>
                                </div>
                                <!-- /.contact-block -->

                                <!-- /.contact-block -->
                            </div>
                            <div class="col-xs-12 col-sm-7 col-md-7 col-md-offset-1 col-lg-offset-2">
                                <div class="section-title clear">
                                    <h3>Send Image</h3>
                                    <span class="bar-dark"></span>
                                    <span class="bar-primary"></span>
                                </div>

                                <form id="contact-form" class="row contact-form no-gutter" action="{% url 'classification:emotionchoice' %}" method="post">
                                    {% csrf_token %}

                                    <div class="col-xs-12 col-sm-12">
                                        <div class="input-field">
                                            <span class= "input-icon" id="subject"><i class="tf-pricetags"></i></span>
                                            <input type="text" class="form-control" name="path" id="path" placeholder="Image path">
                                        </div>
                                    </div> <!-- ./col- -->
                                    
                                    <div class="col-xs-12 col-sm-12">
                                        <div class="input-field">
                                            <span class="btn-border">
                                                <button type="submit" value="Submit" class="btn btn-primary btn-custom-border text-uppercase">Send Image</button>
                                            </span>
                                        </div>
                                    </div> <!-- ./col- -->
                                </form> <!-- /.row -->
                            </div> <!-- /.col- -->
                        </div> <!-- /.row -->
                        
                    </div> <!-- /.container -->

                    
                    <!-- /.container -->

                </div> <!-- /.pt-tablecell -->
            </div> <!-- /.pt-table -->
        </main> <!-- /.site-wrapper -->

        <!-- ================================
        JavaScript Libraries
        ================================= -->
        <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/jquery.easing.min.js' %}"></script>
        <script src="{% static 'js/isotope.pkgd.min.js' %}"></script>
        <script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/jquery-validation.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>